export const envConfig = {
  LOCAL_BASE_URL: process.env.NEXT_PUBLIC_LOCAL_BASE_URL!,
  SERVER_BASE_URL: process.env.NEXT_PUBLIC_SERVER_BASE_URL!,
//   CLOUDINARY_URL: process.env.NEXT_PUBLIC_CLOUDINARY_URL!,
//   CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME!,
//   CLOUDINARY_UPLOAD_PRESET: process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET!,
};